
services:
  expense-tracker:
    build:
      context: .
      args:
        - NODE_ENV=production

    ports:
      - "8000:8000"
    
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}